apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"leader-locking-nfs-client-provisioner","namespace":"default"},"rules":[{"apiGroups":[""],"resources":["endpoints"],"verbs":["get","list","watch","create","update","patch"]}]}
    creationTimestamp: "2021-12-16T06:37:32Z"
    name: leader-locking-nfs-client-provisioner
    namespace: default
    resourceVersion: "3548"
    uid: 048fc60e-ec9c-428e-b150-23e05c212e40
  rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
